sqrtyyy/VampGame

Drakulam/Assets/Prefabs/Human/humancontroller.controller
Drakulam/Assets/Scripts/Character.cs

- change Character.cs file (function FixedUpdate -> Update)
- change transition settings between states

#10 change human animations

---

Drakulam/Assets/Materials.meta
Drakulam/Assets/Prefabs/Map/RoomsCyan.prefab
Drakulam/Assets/Scenes/ViktorScene.unity

RoomsCyan design with walls and floor

#51 RoomsCyan design

---

Drakulam/Assets/Materials.meta
Drakulam/Assets/Prefabs/Map/HallViolet.prefab
Drakulam/Assets/Scenes/Main.unity

- floor, walls
- some decorations (arches, etc.) implemented in ceil layer

#59 hall violet design

---

Drakulam/Assets/Prefabs/Map/TunnelGrey.prefab

#65 tunnel grey design

---

Drakulam/Assets/Prefabs/Map/HallBlue.prefab
Drakulam/Assets/Prefabs/Map/TunnelsPeach.prefab
Drakulam/Assets/Scenes/Main.unity

- pattern on floor,
- water pools
- some decorations implemented in "Ceiling" layer

#46 change HallBlue design

---

Drakulam/Assets/Prefabs/Map/HallRed.prefab
Drakulam/Assets/Scenes/Main.unity

- floor, walls, some decorations

#67 primary HallRed design

---

Drakulam/Assets/Prefabs/Map/RoomsCyan.prefab
Drakulam/Assets/Scenes/Main.unity

move RoomsCyan

---

Drakulam/Assets/Prefabs/Map/HallGreen.prefab

Decorate Hall Green and update prefab

#66 HallGreen design

---

Drakulam/Assets/Scripts/Components/Implementations/HittableCharacter.cs
Drakulam/Assets/Scripts/Components/Implementations/HumanHealth.cs

- character is destroyed after animation finishes

#126 fix character death animation

---

Drakulam/Assets/DecorationBrushes/InteriorCastle/IC_Barrel_Brush.asset
Drakulam/Assets/DecorationBrushes/InteriorCastle/IC_Chandelier_Brush.asset
Drakulam/Assets/DecorationBrushes/InteriorCastle/IC_VaseRed_Brush.asset
Drakulam/Assets/DecorationBrushes/InteriorDungeon/ID_BoxBroken_Brush.asset
Drakulam/Assets/DecorationBrushes/InteriorDungeon/ID_Box_Brush.asset
Drakulam/Assets/DecorationBrushes/InteriorDungeon/ID_Coffin.asset
Drakulam/Assets/DecorationBrushes/InteriorDungeon/ID_Coffin_90_Brush.asset
Drakulam/Assets/DecorationBrushes/InteriorDungeon/ID_Pole.asset
Drakulam/Assets/DecorationBrushes/InteriorDungeon/ID_VaseGreen1-2_Brush.asset
Drakulam/Assets/DecorationBrushes/StructuresCastle/SC_ColumnWide_Brush.asset
Drakulam/Assets/DecorationBrushes/StructuresDungeon/SD_ColumnThin_Short_Brush.asset
Drakulam/Assets/Prefabs/Decorations/InteriorCastle/IC_BarrelBroken.prefab
Drakulam/Assets/Prefabs/Decorations/InteriorDungeon/ID_BoxSmall_broken.prefab
Drakulam/Assets/Prefabs/Decorations/InteriorDungeon/ID_Box_broken.prefab
Drakulam/Assets/Prefabs/Map/HallBlue.prefab

- imlement decortation in hall blue
- update prefab brushes
- remove collider from broken boxes and barrels

#114 hall blue decorations

---

Drakulam/Assets/Art/Map/MapSkelet.meta
Drakulam/Assets/Art/NormalMap.meta
Drakulam/Assets/DecorationBrushes/InteriorDungeon/ID_Pole.asset
Drakulam/Assets/Prefabs/Decorations/InteriorCastle/IC_Barrel.prefab
Drakulam/Assets/Prefabs/Decorations/InteriorCastle/IC_Chandelier.prefab
Drakulam/Assets/Prefabs/Decorations/InteriorCastle/IC_Stump1.prefab
Drakulam/Assets/Prefabs/Decorations/InteriorCastle/IC_VaseGreen.prefab
Drakulam/Assets/Prefabs/Map/TunnelsPeach.prefab

- decorations in tunnels peach
- add new grounddecorative2 layer
- fix some decorations prefabs

#115 tunnels peach decorations

---

Drakulam/Assets/Art/Map/DecorationsSprites/InteriorDungeon.png.meta
Drakulam/Assets/Art/Map/DecorationsSprites/StructuresCastle.png.meta
Drakulam/Assets/Art/Map/DecorationsSprites/StructuresDungeon.png.meta
Drakulam/Assets/Prefabs/Map/HallBlue.prefab
Drakulam/Assets/Scenes/Main.unity

- disable normal maps on decorations

#168 fix bug with decorations display

---

Drakulam/Assets/Scenes/Main.unity

- move pivot point position
- adjust vampire components to new pivot point position

#153 add neccesary vampire components

---

Drakulam/Assets/Art/Vampire/VampireSpriteSheet.png.meta

- adjust pivot point in sprite

#185 fix vampire animation

---

Drakulam/Assets/Prefabs/UI/HumanUI.prefab
Drakulam/Assets/Prefabs/UI/VampireUI.prefab

- larger quest list font
- larger timer font

#183 fix ui elements

---

Drakulam/Assets/Prefabs/Map/MiniMapCamera.prefab

#193 add minimap to ui

---

Drakulam/Assets/Prefabs/Decorations/InteriorCastle/IC_Chandelier/IC_Chandelier.prefab
Drakulam/Assets/Prefabs/Map/HallViolet.prefab

#187 decorations in hall violet

---

Drakulam/Assets/Prefabs/Map/RoomsCyan.prefab

#188 decorations in rooms cyan

---

Drakulam/Assets/Prefabs/Map/HallYellow.prefab

add some decorations to HallYellow prefab map

#199 add Hall Yellow decorations

---

Drakulam/Assets/Materials.meta
Drakulam/Assets/Prefabs/Human/Light.meta
Drakulam/Assets/Prefabs/Map/HallYellow.prefab
Drakulam/Assets/Rendering.meta

-changed decorations to the right layer positions (GroundDecorative)

#199 hall yelow decoration

---

Drakulam/Assets/Materials.meta
Drakulam/Assets/Prefabs/Human/Light.meta
Drakulam/Assets/Prefabs/Map/HallYellow.prefab
Drakulam/Assets/Rendering.meta

-fixed HallYellow prefab (changed brushes and added decorations as GameObjects. Now players can collide with decorations)

#237 fix yellow room decorations

---

Drakulam/Assets/Prefabs/menu/Exit.prefab
Drakulam/Assets/Prefabs/menu/Exit.prefab.meta
Drakulam/Assets/Scripts/menu/MenuExit.cs
Drakulam/Assets/Scripts/menu/MenuExit.cs.meta

-create prefab in Assets/Prefabs/menu named "Exit". Please add it to "MainMenuPanel' in menu scene to use it. (after merge?)

#228_menu_exit

---

Drakulam/Assets/Scripts/MiniGames/DestroyedWall/TaskDestroyedWall.cs
Drakulam/ProjectSettings/ProjectSettings.asset

- move intitialization of _exclamationMark to Awake()

#286 fix exclamation mark on broken wall

---

Drakulam/Assets/Prefabs/Map/HallGreen.prefab

#307 fix unreachable torch in HallGreen

---

Drakulam/Assets/Scripts/Components/Implementations/HumanHealth.cs

-blood prefabs destroying is synchronized
-blood frequency is higher

#284 fixed blood prefab sync.

---

Drakulam/Assets/Prefabs/Human/Resources/Human.prefab
Drakulam/Assets/Prefabs/Vampire/Resources/Vampire.prefab
Drakulam/ProjectSettings/ProjectSettings.asset

-added vampire and human sounds volume dependence from distance

#291 Fix distanced sounds

---

Drakulam/Assets/Scenes/menu.unity
Drakulam/Assets/Scripts/Components/Implementations/CharacterControl.cs
Drakulam/Assets/Scripts/Multiplayer/GameManager.cs
Drakulam/Assets/Scripts/Multiplayer/LobbyManager.cs

- remove the ability to exit the game after it has started
- fix bug with restarting the game

#289 Inability to leave active game
